spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xinshi_admin?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=Zqy@199171
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
xinshi.scheool.transcript.output-dir=/opt/data/xinshi/results/
logging.level.com.xinshi.admin=DEBUG
